name: daizy_tv
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  blur: ^4.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.2.2
  iconsax: ^0.0.8
  infinite_carousel: ^1.1.1
  ionicons: ^0.2.2
  text_scroll: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/background.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        # Add other styles (italic, bold, etc.) if available
        # - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        # - asset: assets/fonts/Poppins/Poppins-Italic.ttf


